### ISSUE TITLE
Exploratory Testing: DI & configuration

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1168]

**Comment by mikary** [comment]
Configuration

connection strings:
* [x] From a single Configuration file
 * [x] No connection string definition
 * [x] ConnectionString defined in context
 * [x] ~~ConnectionStringKey defined in context~~
 * [ ] ConnectionString "Name=xxx" syntax
 * [x] conflicting definition (connection string and key defined) #1391
* [x] Multiple configuration files / overrides #1390
 * [x] Name / Full Name #1395
 * [x] conflicting definition (connection string and key defined in different files) #1390

MaxBatchSize (Relational):
* [x] Load from configuration
* [x] Range validation

CommandTimeout (Relational):
* [x] Load from configuration #1422
* [x] Range validation

DbContextOptionsParser Parser (RawOptions dictionary):
* [x] Key Lookup
* [x] Recursive path (nested properties appear in dictionary)

Migrations:
* Parameterless constructor only (Definition in Startup.cs)
 * [x] Using Configuration
 * [x] Using AddDbContext Action
 * [x] Using OnConfiguring
 * [x] Using Configuration and AddDbContext Action (Action override)
 * [x] Using Configuration, AddDbContext Action, and OnConfiguring override (OnConfiguring 

DI

DbContext constructors and patterns:
* Default
 * [x] Using Configuration
 * [x] Using AddDbContext Action
 * [x] Using OnConfiguring
 * [x] Using Configuration and AddDbContext Action (Action overrides)
 * [x] Using Configuration, AddDbContext Action, and OnConfiguring override (OnConfiguring overrides)
* DbContextOptions
 * [x] Using Configuration (InvalidOperationException)#1401
 * [x] Using AddDbContext Action (InvalidOperationException)
* IServiceProvider
 * [x] Using Configuration
 * [x] Using AddDbContext Action
 * [x] Using Configuration and AddDbContext Action (Action overrides)
* IServiceProvider and DbContextOptions
 * [x] Using Configuration (InvalidOperationException)
 * [x] Using AddDbContext Action (InvalidOperationException)

Verify that we are not creating additional service providers or using the wrong service provider
* Console Application
 * [x] Custom service provider and implicit service provider
  * ServiceProvider.GetService uses calling provider
  * new Context() uses new instance first call and cached for subsequent calls

* Web Application
 * [x] Service provider configured in Startup.CS, injected in Controller
  * New service provider instance created per call (Scoped instance)

* [ ] Passing in connection instance in startup

* [ ] Custom connection implementation

* [ ] Read custom configuration from within DbContext

* [ ] Per instance configuration of DbContext, flowing config to instance
