### ISSUE TITLE
Commands: Assembly-based Command Line Interface (ef.exe)

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#646]
Like `dotnet-ef` but with less `project.json` and more `*.dll`

A rudimentary version of this is available in the `Microsoft.EntityFrameworkCore.Tools` package (under the `tools` directory), but it is currently just an implementation detail of the PMC commands.

A few TODO items to make it generally useful:
- [x] ~~Don't output ANSI escape codes~~ (covered by #6962)
- [x] Review interaction between `--assembly`, `--startup-assembly`, and the working directory
- [x] ~~Fix argument parsing quirks~~ (covered by #6593)
- [x] Review argument defaults
- [ ] ~~Improve the experience of running it on a server~~ (covered by #6313)

**Comment by bricelam** [comment]
We'll probably need a few different versions.

Executable | Description
--- | ---
ef.clr.x86 | 32-bit, Full .NET
ef.clr.any | AnyCPU, Full .NET
ef.coreclr | CoreCLR

We could probably have just and `ef` driver that is smart enough to delegate based on the assemblies passed in.

**Comment by bricelam** [comment]
(Pulling this into 1.0.1 since it is has become an implementation detail of #5334.)

**Comment by rowanmiller** [comment]
Reopening as we have not really provided this feature. We have ef.exe, but it is not ready for developers to interact with - it is used internally by PowerShell commands and dotnet-ef.

**Comment by rowanmiller** [comment]
@bricelam investigated and confirmed that the user experience of calling ef.exe directly is not good enough to say that we have provided this feature.

**Comment by bricelam** [comment]
A few TODO items:
- [ ] Don't output ANSI escape codes (covered by #6962)
- [ ] Review interaction between `--assembly`, `--startup-assembly`, and the working directory
- [ ] Consider removing `--no-color`
- [ ] Fix argument parsing quirks (covered by #6593)
- [ ] Review argument defaults

**Comment by bricelam** [comment]
Currently, `--assembly` always has to be specified. Does anyone think it should be positional instead?
```sh
# Current
ef migration list --assembly WebApplication1.dll

# Possible
ef migrations list WebApplication1.dll
ef database update WebApplication1.dll Migration7
```

Or is it too awkward when combined with sub-commands and other positional arguments?

**Comment by bricelam** [comment]
We've decided to leave `--assembly` as a named parameter.

**Comment by bricelam** [comment]
I believe it's ready for prime time. I've filed aspnet/EntityFramework.Docs#328 to document it.

**Comment by andycmaj** [comment]
hello... not understanding which versions `--assembly` is expected to work in...

i'm trying to run migrations on a published dll and `--assembly` doesn't seem to fix the missing project error:

```bash
root@82332f775c88:/app# dotnet exec --depsfile KanbanLab.FrontEnd.deps.json --runtimeconfig KanbanLab.FrontEnd.runtimeconfig.json Microsoft.EntityFrameworkCore.Design.dll database update --assembly KanbanLab.FrontEnd.dll --startup-assembly KanbanLab.FrontEnd.dll --verbose --context KanbanContext

Unhandled Exception: System.MissingMethodException: Entry point not found in assembly 'Microsoft.EntityFrameworkCore.Design, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Aborted
root@82332f775c88:/app# dotnet exec --depsfile KanbanLab.FrontEnd.deps.json --runtimeconfig KanbanLab.FrontEnd.runtimeconfig.json dotnet-ef.dll database update --assembly KanbanLab.FrontEnd.dll --startup-assembly KanbanLab.FrontEnd.dll --verbose --context KanbanContext
Microsoft.EntityFrameworkCore.Tools.CommandException: No project was found. Change the current working directory or use the --project option.
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.FindProjects(String path, String errorWhenNoProject, String errorWhenMultipleProjects)
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
No project was found. Change the current working directory or use the --project option.
root@82332f775c88:/app# dotnet exec --depsfile KanbanLab.FrontEnd.deps.json --runtimeconfig KanbanLab.FrontEnd.runtimeconfig.json dotnet-ef.dll --assembly KanbanLab.FrontEnd.dll --startup-assembly KanbanLab.FrontEnd.dll database update --verbose --context KanbanContext

                     _/\__
               ---==/    \\
         ___  ___   |.    \|\
        | __|| __|  |  )   \\\
        | _| | _|   \_/ |  //|\\
        |___||_|       /   \\\/\\

Entity Framework Core .NET Command-line Tools 2.1.0-preview1-28290

Usage: dotnet ef [options] [command]

Options:
  --version        Show version information
  -h|--help        Show help information
  -v|--verbose     Show verbose output.
  --no-color       Don't colorize output.
  --prefix-output  Prefix output with level.

Commands:
  database    Commands to manage the database.
  dbcontext   Commands to manage DbContext types.
  migrations  Commands to manage migrations.

Use "dotnet ef [command] --help" for more information about a command.
root@82332f775c88:/app# ef
bash: ef: command not found
root@82332f775c88:/app# dotnet dotnet-ef.dll
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/app/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /app/dotnet-ef.runtimeconfig.json file specifying the appropriate framework.
root@82332f775c88:/app# dotnet exec --depsfile KanbanLab.FrontEnd.deps.json --runtimeconfig KanbanLab.FrontEnd.runtimeconfig.json dotnet-ef.dll --assembly KanbanLab.FrontEnd.dll --startup-assembly KanbanLab.FrontEnd.dll database update --verbose --context KanbanContext

                     _/\__
               ---==/    \\
         ___  ___   |.    \|\
        | __|| __|  |  )   \\\
        | _| | _|   \_/ |  //|\\
        |___||_|       /   \\\/\\

Entity Framework Core .NET Command-line Tools 2.1.0-preview1-28290

Usage: dotnet ef [options] [command]

Options:
  --version        Show version information
  -h|--help        Show help information
  -v|--verbose     Show verbose output.
  --no-color       Don't colorize output.
  --prefix-output  Prefix output with level.

Commands:
  database    Commands to manage the database.
  dbcontext   Commands to manage DbContext types.
  migrations  Commands to manage migrations.

Use "dotnet ef [command] --help" for more information about a command.
```

**Comment by andycmaj** [comment]
ended up snatching `ef.dll` from the package cache during my builds...

```
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.1.0-preview1-final" />
    <Content CopyToPublishDirectory="PreserveNewest" Include="$(NuGetPackageRoot)microsoft.entityframeworkcore.tools.dotnet\2.1.0-preview1-final\tools\netcoreapp2.0\*.*" />
```

so now i can publish with `ef.dll` and this seems to actually work for migrations, rather than `dotnet-ef.dll`
