### ISSUE TITLE
Test EF Core 2.0 with UWP 6.0

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework#9281]
The upcoming version of UWP comes with support for .NET Standard 2.0 and we want to test EF Core 2.0 bits on it to makes sure we... 

1. Get a chance to identify any blockers that can be fixed in UWP or .NET Native before their release
2. Identify anything we could do in EF Core to improve UWP compatibility after 2.0
3. Understand how both technologies are working together at this stage, in particular in regards to other issues previously reported, so that we can provide clearer guidance to customers on what is supported whether to rely on EF Core 2.0 on UWP 6.0.

The plan is to test the following general areas:

1. [x] Query
   1. [x] Anonymous types (see #5119)
   2. [x] Nullable enums (see #6537, #8188)
   3. [x] Navigation properties (see #5841, #9012)
   4. [x] Complex queries (see #6423)
2. [ ] ~~Change tracking performance (see #7582)~~ Still an issue
3. [x] SaveChanges (see #7614)
4. [ ] ~~Migrations~~ Fails due to `System.Globalization.CultureInfo` unification failure
   1. [x] Data Annotations (see #9141)
5. [ ] ~~Reverse Engineering~~ Not supported
6. [x] SQL Server
7. [x] Sqlite

**Comment by bricelam** [comment]
Reverse engineering into a UWP project won't work, but I'm curious to see if we have a good error...

**Comment by bricelam** [comment]
(In theory, it could work with a purly managed ADO.NET provider.)

**Comment by divega** [comment]
@bricelam curious, why is that? 

BTW, we expect to be testing fully managed SqlClient for UWP as part of this. You just reminded me I did not add it to the list :smile:

**Comment by bricelam** [comment]
NuGet will restore for UWP, but we run the tools on .NET Framework. You'll get the "no app sandbox" error.

**Comment by bricelam** [comment]
I've directed a few people towards using the managed SqlClient implementation for UWP on ARM, and they've all reported success, so I'm hopeful it will go well.

**Comment by AndriySvyryd** [comment]
@bricelam 
>PM> Scaffold-DbContext "Data Source=Verification.db" Microsoft.EntityFrameworkCore.Sqlite
System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The process has no package identity. (Exception from HRESULT: 0x80073D54)
   at Windows.Storage.ApplicationData.get_Current()
   at SQLitePCL.SQLite3Provider_e_sqlite3..ctor()
   at SQLitePCL.Batteries_V2.Init()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.SqliteDatabaseModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ModelScaffolder.Generate(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String projectPath, String outputPath, String rootNamespace, String contextName, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

**Comment by bricelam** [comment]
We should look into wrapping that HRESULT. Something like...

> The current provider `Microsoft.EntityFrameworkCore.Sqlite` can't connect to databases from UWP projects at design time. Consider running this command in a separate project targeting a supported framework.

**Comment by AndriySvyryd** [comment]
@bricelam For SQL Server the exception is:
> System.TypeLoadException: Could not load type 'System.MarshalByRefObject' from assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.SqlServerDatabaseModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ModelScaffolder.Generate(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String projectPath, String outputPath, String rootNamespace, String contextName, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

**Comment by bricelam** [comment]
Hmm... `MarshalByRefObject` is part of .NET Standard 2.0

**Comment by divega** [comment]
@bricelam could a binding redirect help?

**Comment by bricelam** [comment]
I don't think so. I think the facade is just missing a type forward.

**Comment by AndriySvyryd** [comment]
@divega, @ajcvickers  These are my final findings:
EF 2.0.1 prerelease can be used with UWP 6.0.0 prerelease without major issues with InMemory, SQLite or SQL Server providers.

To get acceptable change tracking performance `ChangingAndChangedNotifications` strategy should be used.

To use the design time tools (Migrations and Scaffolding) the context and model should be placed in a netstandard2.0 project and the tools should be executed from a .NET Core project.

**Comment by IngoBleile** [comment]
With the lastest previews of everything I am still getting

"Could not load type 'System.Globalization.CultureInfo' from assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'"

when using "add-migration" with a .NET Standard 2.0 class library (I am using EF SQLite).

**Comment by bricelam** [comment]
@IngoBleile When EF Core 2.0.1 is release, UWP projects will be blocked. You'll need to use a separate .NET Standard class library cross-targeting either .NET Framework or .NET Core.

**Comment by IngoBleile** [comment]
@bricelam: You mean like that?

<TargetFrameworks>netstandard2.0;net462</TargetFrameworks> or
<TargetFrameworks>netstandard2.0;netcoreapp2.0</TargetFrameworks>

in the .NET Standard 2.0 class library with EF? Neither of it works.

**Comment by bricelam** [comment]
I Visual Studio just picks the first framework listed. Try swapping the order so that .NET Framework/.NET Core is listed first.

If you happen to be using `dotnet ef`, you can specify the desired framework using `--framework`.

**Comment by IngoBleile** [comment]
No, not working.

**Comment by AndriySvyryd** [comment]
@IngoBleile I just tried it with the pre-release 2.0.1 version of EF and this works:

`<TargetFrameworks>netcoreapp2.0;netstandard2.0</TargetFrameworks>`

You need 2.0.1 to be able to compile in release mode anyway, so please wait until it's released
